# Site Settings
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "clean" # Provides a crisp, high-contrast, professional tech aesthetic

title: "Moses Karanja Thuo"
description: "Cybersecurity & Digital Forensics Portfolio"
url: "https://ThuoKaranja.github.io"
baseurl: ""

# Site Author Defaults
author:
  name: "Moses Karanja Thuo"
  avatar: "/assets/images/photo_2026-05-21_21-36-41.jpg"
  bio: "Cybersecurity & Digital Forensics Student | Ethical Hacker | Cyber Threat Analyst"
  location: "Kitale, Kenya"
  links:
    - label: "Download CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/Moses_Karanja_CV.pdf"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:moseskanji254@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cyberdefend254"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ThuoKaranja"
      

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true # Keeps your sleek profile visible on the left sidebar
      sidebar:
        nav: "docs"
# Plugins Required by Minimal Mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
